/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.segvek.terminal.interactiv;

import com.segvek.terminal.interactiv.model.Admission;
import com.segvek.terminal.interactiv.model.DependencyAdmission;
import com.segvek.terminal.interactiv.model.DrainLocation;
import com.segvek.terminal.interactiv.model.Estakada;
import com.segvek.terminal.interactiv.model.Tank;
import com.segvek.terminal.interactiv.model.TypeEstakada;
import com.segvek.terminal.interactiv.model.TypeTank;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author Panas
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        TypeEstakada t1=new TypeEstakada(1L,"Авто");
        TypeEstakada t2=new TypeEstakada(2L,"ж/д");
        ArrayList<Estakada> estakads = new ArrayList<>();
        
        ArrayList<DrainLocation> dll1 = new ArrayList<>();
        Estakada e1 = new Estakada(1L, t1, "1",dll1); 
        dll1.add(new DrainLocation(1L, 1,e1));
        dll1.add(new DrainLocation(2L, 2,e1));
        dll1.add(new DrainLocation(3L, 3,e1));
        dll1.add(new DrainLocation(4L, 4,e1));
        estakads.add(e1);
        
        ArrayList<DrainLocation> dll3 = new ArrayList<>();
        Estakada e3 = new Estakada(3L, t2, "1",dll3);
        dll3.add(new DrainLocation(9L, 1,e3));
        dll3.add(new DrainLocation(10L, 2,e3));
        estakads.add(e3);
        
        
        ArrayList<DrainLocation> dll2 = new ArrayList<>();
        Estakada e2 = new Estakada(2L, t1, "2",dll2);
        dll2.add(new DrainLocation(5L, 1,e2));
        dll2.add(new DrainLocation(6L, 2,e2));
        dll2.add(new DrainLocation(7L, 3,e2));
        dll2.add(new DrainLocation(8L, 4,e2));
        estakads.add(e2);
        
        
        
        ((InteractivGrafic)jPanel1).setEstakads(estakads);
        
        
        
        TypeTank tt1 = new TypeTank(1L, 50, 30);
        TypeTank tt2 = new TypeTank(2L, 70, 60);
        ArrayList<Admission> admissions = new ArrayList<>();
        
        Tank ta1 = new Tank(1L, "AB 4573 BK", tt1);
        Tank ta2 = new Tank(1L, "AX 4825 PO", tt1);
        Tank ta3 = new Tank(1L, "KE 2953 TW", tt1);
        
        Admission a1 = new Admission(1L,ta1, new Date(117,7,3,6,20), new Date(117,7,2,7,10), new DrainLocation(6L, 2,e2));
        Admission a2 = new Admission(2L,ta2, new Date(117,7,3,15,20), new Date(117,7,2,16,10), new DrainLocation(3L, 3,e1),"Виконано");
        Admission a3 = new Admission(3L,ta3, new Date(117,7,3,8,20), new Date(117,7,2,9,10), new DrainLocation(6L, 2,e2));       
        
        admissions.add(a1);
        admissions.add(a2);
        admissions.add(a3);
        
        
        
        ArrayList<Admission> indepa1 = new ArrayList<>();
        indepa1.add(a3);
        a1.setIndepented(indepa1);
        
        ArrayList<Admission> depa3 = new ArrayList<>();
        depa3.add(a1);
        a3.setDepend(depa3);
        
        ArrayList<DependencyAdmission> das = new ArrayList<>();
        das.add(new DependencyAdmission(a1, a3));
        
        
        ((InteractivGrafic)jPanel1).setDependencyAdmissions(das);
        ((InteractivGrafic)jPanel1).setAdmissions(admissions);
        ((InteractivGrafic)jPanel1).init();
        addKeyListener(((InteractivGrafic)jPanel1).getContent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new InteractivGrafic();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
